earphans/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^firstapp/', include('firstapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstapp/urls.py
from django.conf.urls import url

from . import views

# namespace for urls
app_name = 'firstapp'

urlpatterns = [
    url(r'^earphones/$', views.ListEarphonesView.as_view(), name='earphones'),

    url(r'^earphones/search/$', views.SearchForEarphones, name='search-for-earphones'),

    url(r'^earphones/search/(?P<earphone_feature>[\w\-]+)/$', views.RedirectForEarphonesFeatures, name='redirect-for-earphones-features'),

    url(r'^$', views.IndexView.as_view(), name='index'),

    # ex: /firstapp/5
    # r, raw, It tells Python that a string is "raw", that nothing in the string should be escaped.
    # ^, start
    # (?P<name>pattern), where name is the name of the group and pattern is some pattern to match.
    # pk, The DetailView generic view expects the primary key value captured from the URL to be called "pk", so we've changed question_id to pk for the generic views.
    # $, finish
    # name, this field can be used in tag 'url' in template
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # ex: /firstapp/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),

    # ex: /firstapp/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

firstapp/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return timezone.now() > self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    # ForeignKey: you will automagically get the inverse relation on instances of the question model back to the set of possible choices.
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Earphone(models.Model):
    EARPHONE_TYPE_CHOICES = (
        ('Earbud', 'Earbud'),
        ('Over-Ear', 'Over-Ear'),
        ('On-Ear', 'On-Ear'),
    )
    EARPHONE_FEATURES = (
        ('Wireless', 'Wireless'),
        ('Microphone', 'Microphone'),
        ('Phone-Control', 'Phone-Control')
    )
    earphone_name = models.CharField(null=True, max_length=100)
    brand_name = models.CharField(null=True, max_length=100)
    earphone_type = models.CharField(null=True, max_length=10, choices=EARPHONE_TYPE_CHOICES)
    price = models.PositiveIntegerField()
    earphone_features = ArrayField(
        models.CharField(max_length=20, choices=EARPHONE_FEATURES),
        size=10,
        blank=True,
        default=[],
        help_text='values like Wireless,Microphone,Phone Control...',
    )
    earphone_image = models.ImageField(null=True, upload_to='uploads/earphone_images/', blank=True)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.earphone_name

firstapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Question, Choice, Earphone

# Create views through generic views here.
class ListEarphonesView(generic.ListView):
    template_name = 'firstapp/list_earphones.html'
    model = Earphone

def SearchForEarphones(request):
    query_string = request.GET.get("query-string", False)
    earphone_type = request.GET.get("earphone-type", False)
    earphone_features = []
    earphone_features.append(request.GET.get("earphone-feature-wireless", False))
    earphone_features.append(request.GET.get("earphone-feature-microphone", False))
    earphone_features.append(request.GET.get("earphone-feature-phone-control", False))
    earphones_list = Earphone.objects.all()

    # search for names, brands
    if query_string:
        earphones_list = Earphone.objects.filter(earphone_name__search=query_string)

    # search for types
    if earphone_type:
        earphones_list = earphones_list.filter(earphone_type__search=earphone_type)

    # search for features
    earphones_list = SearchForEarphonesFeatures(earphones_list, earphone_features)

    context = {
        'query_string': query_string,
        'earphone_type': earphone_type,
        'earphone_features': earphone_features,
        'earphones_list': earphones_list,
    }

    return render(request, 'firstapp/search_result_of_earphones.html', context)

def SearchForEarphonesFeatures(earphones_list, features_list):
    for feature in features_list:
        if feature:
            earphones_list = earphones_list.filter(earphone_features__contains=[feature]) 
    return earphones_list

def RedirectForEarphonesFeatures(request, earphone_feature):
    earphones_list = Earphone.objects.all()
    if earphone_feature:
        earphones_list = earphones_list.filter(earphone_features__contains=[earphone_feature])
    context = {
        'earphone_feature': earphone_feature,
        'earphones_list': earphones_list,
    }
    return render(request, 'firstapp/search_result_of_earphones.html', context)

# ---------------------
# codes for experiments
# ---------------------

class IndexView(generic.ListView):
    template_name = 'firstapp/index.html'
    model = Question

    # change the object name of context
    # from default 'object_list' to 'latest_question_list'
    # context_object_name = 'latest_question_list'

    # By default, get_queryset() returns the value of the 'queryset' attribute
    # if it is set, otherwise it constructs a QuerySet
    # by calling the all() method on the model attribute's default manager.
    #
    # 'queryset': A QuerySet that represents the objects. If provided,
    # the value of queryset supersedes the value provided for model.
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte = timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'firstapp/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'firstapp/results.html'

# def index(request):
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    context = {
#        'latest_question_list': latest_question_list,
#    }
#    return render(request, 'firstapp/index.html', context)

def detail(request, question_id):
    """
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    """
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'firstapp/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'firstapp/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        # choice_set: choice_set is a RelatedManager which can create querysets of Choice objects which relate to the Question instance, e.g. q.choice_set.all()
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'firstapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        # save() when INSERT or UPDATE the database
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('firstapp:results', args=(question.id,)))

firstapp/templates/firstapp/base.html
{% load static %}
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'firstapp/style.css' %}?={% now "U" %}" />
	<body>
		<div class="page-header">
			<h1><a href="{% url 'firstapp:earphones' %}">Earphans</a></h1>
		</div>
		<div class="content" id="above-content">
			{% block above-content %}
			{% endblock %}
		</div>
		<div class="content" id="main-content">
			{% block content %}
			{% endblock %}
		</div>
	</body>

firstapp/templates/firstapp/base_search_for_earphones.html
{% extends 'firstapp/base.html' %}
{% block above-content %}
	<div>
		<div>
			<form action="{% url 'firstapp:search-for-earphones' %}" method="get">
			{% csrf_token %}
				<input type="text" name="query-string" />
				<input type="submit" value="search" />
				<br>
				<span>Types: </span>
				<input type="radio" name="earphone-type" id="type-earbunds" value="Earbud"/>
				<label for="type-earbunds">Earbud</label>
				<input type="radio" name="earphone-type" id="type-earbunds" value="On-Ear"/>
				<label for="type-earbunds">On-ear</label>
				<input type="radio" name="earphone-type" id="type-earbunds" value="Over-Ear"/>
				<label for="type-earbunds">Over-ear</label>
				<br>
				<span>Features: </span>
				<input type="radio" name="earphone-feature-wireless" id="feature-wireless" value="Wireless"/>
				<label for="feature-wireless">Wireless</label>
				<input type="radio" name="earphone-feature-microphone" id="feature-microphone" value="Microphone"/>
				<label for="feature-microphone">Microphone</label>
				<input type="radio" name="earphone-feature-phone-control" id="feature-phone-control" value="Phone-Control"/>
				<label for="feature-phone-control">Phone-Control</label>
			</form>
		</div>
	</div>
{% endblock above-content %}

firstapp/templates/firstapp/detail.html
{% extends 'firstapp/base.html' %}
{% block content %}
	<div>
		<h1>{{ question.question_text }}</h1>

		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

		<form action="{% url 'firstapp:vote' question.id %}" method="post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
		    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
		    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
		{% endfor %}
		<input type="submit" value="Vote" />
		</form>
	</div>
{% endblock content %}

firstapp/templates/firstapp/index.html
{% extends 'firstapp/base.html' %}
{% block content %}
	{% if object_list %}
	{# self.object_list will contain the list of objects (usually, but not necessarily a queryset) that the view is operating upon #}
		<div>
		    <ul>
		    {% for question in object_list %}
		        <li><a href="{% url 'firstapp:detail' question.id %}">{{ question.question_text }}</a></li>
		    {% endfor %}
		    </ul>
		</div>
	{% else %}
	    <p>No firstapp are available.</p>
	{% endif %}
{% endblock content %}

firstapp/templates/firstapp/list_earphones.html
{% extends 'firstapp/base_search_for_earphones.html' %}
{% block content %}
	{% if object_list %}
	{# self.object_list will contain the list of objects (usually, but not necessarily a queryset) that the view is operating upon #}
		<div>
		    {% for earphone in object_list %}
			<ul>
		        <li><a href="">{{ earphone.earphone_name }}</a></li>
		        <li>{{ earphone.brand_name }}</li>
		        <li>{{ earphone.price }}</li>
		        <li>{{ earphone.earphone_type }}</li>
		        <li>
			    {% for feature in earphone.earphone_features %}
					{{ feature }}
			    {% endfor %}
		        </li>
		        <li><img src="{{ earphone.earphone_image.url }}" /></li>
		    </ul>
		    {% endfor %}
		</div>
	{% else %}
	    <p>No earphones are available.</p>
	{% endif %}
{% endblock content %}

firstapp/templates/firstapp/results.html
{% extends 'firstapp/base.html' %}
{% block content %}
	<div>
		<h1>{{ question.question_text }}</h1>

		<ul>
		{% for choice in question.choice_set.all %}
		    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes|pluralize }}</li>
		{% endfor %}
		</ul>

		<a href="{% url 'firstapp:detail' question.id %}">Vote again?</a>
	</div>
{% endblock content %}

firstapp/templates/firstapp/search_for_earphones.html
{% extends 'firstapp/base.html' %}
{% load static %}
{% block content %}
	<div>
		<p>search for {{ query_string }}, type: {{ earphone_type }}, feature: {{ earphone_feature }}</p>
		{% for earphone in earphones_list %}
			<ul>
				<li>{{ earphone.earphone_name }}</li>
				<li>{{ earphone.brand_name }}</li>
		        <li>{{ earphone.price }}</li>
		        <li>{{ earphone.earphone_type }}</li>
		        <li>
			    {% for feature in earphone.earphone_features %}
					{{ feature }}
			    {% endfor %}
		        </li>
		        <li><img src="{{ earphone.earphone_image.url }}" /></li>
			</ul>
		{% endfor %}
	</div>
{% endblock content %}

firstapp/templates/firstapp/search_result_of_earphones.html
{% extends 'firstapp/base_search_for_earphones.html' %}
{% block content %}
	<p>search for {{ query_string }}, type: {{ earphone_type }}, feature: {{ earphone_feature }}</p>
	<div>
		{% if earphones_list %}
			{% for earphone in earphones_list %}
				<ul>
					<li>{{ earphone.earphone_name }}</li>
					<li>{{ earphone.brand_name }}</li>
			        <li>{{ earphone.price }}</li>
			        <li>{{ earphone.earphone_type }}</li>
			        <li>
				    {% for feature in earphone.earphone_features %}
						{{ feature }}
				    {% endfor %}
			        </li>
			        <li><img src="{{ earphone.earphone_image.url }}" /></li>
				</ul>
			{% endfor %}
		{% else %}
			<p>No earphones are available.</p>
		{% endif %}
	</div>
{% endblock content %}